import Head from 'next/head'
import Abstract from './components/Abstract'
import Bio from './components/Bio'
import Name from './components/Name'
import OnTheWeb from './components/OnTheWeb'
import TopContent from './components/TopContent'
import Works from './components/Works'
const Home = () => {
  return (
    <div>
      <Head>
        <title>Kazuma Kurisaki Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopContent></TopContent>
      <div className="flex justify-center">
        <div className="w-[60%]">
          <Name></Name>
          <Abstract></Abstract>
          <OnTheWeb></OnTheWeb>
          <Works></Works>
          <Bio></Bio>
        </div>
      </div>
    </div>
  )
}

export default Home
